import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import NextThemeProvider from './components/NextThemeProvider';
import Header from './components/Header';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: '서동경 포트폴리오',
    description: 'Generated by create SEODONGKYEONG',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className="bg-primary">
                <NextThemeProvider>
                    <Header />
                    {children}
                    <Footer />
                </NextThemeProvider>
            </body>
        </html>
    );
}
